[versions]
agp = "8.13.1"
kotlin = "2.2.21"
ksp = "2.3.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.11.0"
activityCompose = "1.11.0"
composeBom = "2025.11.00"
constraintlayout = "2.2.1"
lifecycleRuntimeKtx = "2.9.4"
lifecycleLivedataKtx = "2.9.4"
lifecycleViewmodelKtx = "2.9.4"
retrofit = "3.0.0"
okhttp = "5.3.0"
okhttpUrlConnection = "5.3.0"
koin = "4.1.1"
log = "1.5.1"
lottie = "6.7.1"
glide = "5.0.5"
coil = "2.7.0"
glideLegacySupportV4 = "1.0.0"
glideCompiler = "5.0.5"
sdpAndroid = "1.1.1"
material3Android = "1.4.0"
androidx_splash_screen = "1.2.0"
room = "2.8.3"
foundation = "1.9.4"
accompanist = "0.36.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }

# architecture components
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-lifecycle-runtime-ktx ={ group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-livedata-ktx ={ group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-lifecycle-viewmodel-ktx ={ group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }

# compose
androidx-lifecycle-compose = {group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelKtx"}
androidx-lifecycle-compose-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

# retrofit2
retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit2-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
retrofit2-converter-scalars = { group = "com.squareup.retrofit2", name = "converter-scalars", version.ref = "retrofit" }
retrofit2-adapter-rxjava2 = { group = "com.squareup.retrofit2", name = "adapter-rxjava2", version.ref = "retrofit" }

# loggin interceptor for networking
okhttp3-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp3-urlconnection = { group = "com.squareup.okhttp3", name = "okhttp-urlconnection", version.ref = "okhttpUrlConnection" }

# koin
koin =  { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-android-compat =  { group = "io.insert-koin", name = "koin-android-compat", version.ref = "koin" }
koin-androidx-workmanager =  { group = "io.insert-koin", name = "koin-androidx-workmanager", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }

# Log
log = { group = "com.github.ajalt", name = "timberkt", version.ref = "log" }

# lottie
lottie =  { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }

# glide
glide =  { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-legacy-support-v4 =  { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "glideLegacySupportV4" }
glide-compiler =  { group = "com.github.bumptech.glide", name = "ksp", version.ref = "glideCompiler" }

#coil image
coil =  { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

#
sdp-android = { group = "com.intuit.sdp", name = "sdp-android", version.ref = "sdpAndroid"}
ssp-android = { group = "com.intuit.ssp", name = "ssp-android", version.ref = "sdpAndroid"}

# material3
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }
androidx-material-icons-android = { group = "androidx.compose.material", name = "material-icons-extended" }

# splash screen
androidx_splash_screen = { module = "androidx.core:core-splashscreen", version.ref = "androidx_splash_screen"}

# room
room_compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room_ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room_runtime = { module = "androidx.room:room-runtime", version.ref = "room" }

# Compose Foundation
foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation"}
accompanist = { group = "com.google.accompanist", name = "accompanist-pager", version.ref = "accompanist"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

